// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIMb9E8U8-zJCh9KszD18Y1-yIz0j9jWk',
    appId: '1:791332966723:web:4c38a60df81ae5697a1ff6',
    messagingSenderId: '791332966723',
    projectId: 'elver-app-db9f8',
    authDomain: 'elver-app-db9f8.firebaseapp.com',
    storageBucket: 'elver-app-db9f8.firebasestorage.app',
    measurementId: 'G-DB0DDNZB3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdCS4TOLV9o5vYMixGkQV7L_m9iEyxgSQ',
    appId: '1:791332966723:android:acd0fbfccd5168607a1ff6',
    messagingSenderId: '791332966723',
    projectId: 'elver-app-db9f8',
    storageBucket: 'elver-app-db9f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpdVRZoh5aUgr_MVBYL_k008KMBaXPF78',
    appId: '1:791332966723:ios:02586bdcdf31da3c7a1ff6',
    messagingSenderId: '791332966723',
    projectId: 'elver-app-db9f8',
    storageBucket: 'elver-app-db9f8.firebasestorage.app',
    iosBundleId: 'com.example.elverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpdVRZoh5aUgr_MVBYL_k008KMBaXPF78',
    appId: '1:791332966723:ios:02586bdcdf31da3c7a1ff6',
    messagingSenderId: '791332966723',
    projectId: 'elver-app-db9f8',
    storageBucket: 'elver-app-db9f8.firebasestorage.app',
    iosBundleId: 'com.example.elverApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIMb9E8U8-zJCh9KszD18Y1-yIz0j9jWk',
    appId: '1:791332966723:web:942f754202a85e6f7a1ff6',
    messagingSenderId: '791332966723',
    projectId: 'elver-app-db9f8',
    authDomain: 'elver-app-db9f8.firebaseapp.com',
    storageBucket: 'elver-app-db9f8.firebasestorage.app',
    measurementId: 'G-8RFYH8RG2J',
  );
}
